// 由 generate_logos.py 自动生成，请勿手动编辑；新增 LOGO 请改脚本后重跑。
// 常用网站预设 LOGO：统一 128x128 圆角方形 + 品牌渐变 + 白色符号
export const PRESET_LOGOS = [
  { id: 'baidu', name: '百度', cat: '搜索', color: '#2932E1', file: 'images/logos/baidu.svg', domains: ['baidu.com'] },
  { id: 'google', name: 'Google', cat: '搜索', color: '#ffffff', file: 'images/logos/google.svg', domains: ['google.com', 'google.com.hk'] },
  { id: 'bing', name: '必应', cat: '搜索', color: '#00788C', file: 'images/logos/bing.svg', domains: ['bing.com', 'cn.bing.com'] },
  { id: 'bilibili', name: '哔哩哔哩', cat: '视频', color: '#FB7299', file: 'images/logos/bilibili.svg', domains: ['bilibili.com'] },
  { id: 'youtube', name: 'YouTube', cat: '视频', color: '#CC0000', file: 'images/logos/youtube.svg', domains: ['youtube.com', 'youtu.be'] },
  { id: 'douyin', name: '抖音', cat: '视频', color: '#101010', file: 'images/logos/douyin.svg', domains: ['douyin.com'] },
  { id: 'vqq', name: '腾讯视频', cat: '视频', color: '#E8380D', file: 'images/logos/vqq.svg', domains: ['v.qq.com'] },
  { id: 'iqiyi', name: '爱奇艺', cat: '视频', color: '#00A005', file: 'images/logos/iqiyi.svg', domains: ['iqiyi.com'] },
  { id: 'youku', name: '优酷', cat: '视频', color: '#0055E0', file: 'images/logos/youku.svg', domains: ['youku.com'] },
  { id: 'mangotv', name: '芒果TV', cat: '视频', color: '#FF6A00', file: 'images/logos/mangotv.svg', domains: ['mgtv.com'] },
  { id: 'weibo', name: '微博', cat: '社交', color: '#E6162D', file: 'images/logos/weibo.svg', domains: ['weibo.com'] },
  { id: 'zhihu', name: '知乎', cat: '社交', color: '#0066CC', file: 'images/logos/zhihu.svg', domains: ['zhihu.com'] },
  { id: 'xiaohongshu', name: '小红书', cat: '社交', color: '#FF2442', file: 'images/logos/xiaohongshu.svg', domains: ['xiaohongshu.com'] },
  { id: 'douban', name: '豆瓣', cat: '社交', color: '#00A015', file: 'images/logos/douban.svg', domains: ['douban.com'] },
  { id: 'tieba', name: '百度贴吧', cat: '社交', color: '#2B6CD4', file: 'images/logos/tieba.svg', domains: ['tieba.baidu.com'] },
  { id: 'x', name: 'X / Twitter', cat: '社交', color: '#000000', file: 'images/logos/x.svg', domains: ['x.com', 'twitter.com'] },
  { id: 'wechat', name: '微信', cat: '社交', color: '#07A850', file: 'images/logos/wechat.svg', domains: ['weixin.qq.com', 'wechat.com'] },
  { id: 'github', name: 'GitHub', cat: '开发', color: '#16191D', file: 'images/logos/github.svg', domains: ['github.com'] },
  { id: 'gitee', name: 'Gitee', cat: '开发', color: '#C71D23', file: 'images/logos/gitee.svg', domains: ['gitee.com'] },
  { id: 'csdn', name: 'CSDN', cat: '开发', color: '#FC5531', file: 'images/logos/csdn.svg', domains: ['csdn.net'] },
  { id: 'juejin', name: '掘金', cat: '开发', color: '#1E5EFF', file: 'images/logos/juejin.svg', domains: ['juejin.cn'] },
  { id: 'stackoverflow', name: 'Stack Overflow', cat: '开发', color: '#F48024', file: 'images/logos/stackoverflow.svg', domains: ['stackoverflow.com'] },
  { id: 'mdn', name: 'MDN', cat: '开发', color: '#050505', file: 'images/logos/mdn.svg', domains: ['developer.mozilla.org'] },
  { id: 'taobao', name: '淘宝', cat: '购物', color: '#FF5000', file: 'images/logos/taobao.svg', domains: ['taobao.com', 'tmall.com'] },
  { id: 'jd', name: '京东', cat: '购物', color: '#C8161D', file: 'images/logos/jd.svg', domains: ['jd.com'] },
  { id: 'pdd', name: '拼多多', cat: '购物', color: '#E22E1F', file: 'images/logos/pdd.svg', domains: ['pinduoduo.com'] },
  { id: 'meituan', name: '美团', cat: '购物', color: '#FFC300', file: 'images/logos/meituan.svg', domains: ['meituan.com', 'dianping.com'] },
  { id: 'baidu-pan', name: '百度网盘', cat: '工具', color: '#0090E0', file: 'images/logos/baidu-pan.svg', domains: ['pan.baidu.com'] },
  { id: 'aliyun-pan', name: '阿里云盘', cat: '工具', color: '#0090E0', file: 'images/logos/aliyun-pan.svg', domains: ['aliyundrive.com', 'alipan.com'] },
  { id: 'gmail', name: 'Gmail', cat: '工具', color: '#F1F1F1', file: 'images/logos/gmail.svg', domains: ['mail.google.com'] },
  { id: 'qqmail', name: 'QQ邮箱', cat: '工具', color: '#0052D9', file: 'images/logos/qqmail.svg', domains: ['mail.qq.com'] },
  { id: 'notion', name: 'Notion', cat: '工具', color: '#EFEFEF', file: 'images/logos/notion.svg', domains: ['notion.so'] },
  { id: 'netease-music', name: '网易云音乐', cat: '音乐', color: '#C20C0C', file: 'images/logos/netease-music.svg', domains: ['music.163.com'] },
  { id: 'qqmusic', name: 'QQ音乐', cat: '音乐', color: '#22B573', file: 'images/logos/qqmusic.svg', domains: ['y.qq.com'] },
  { id: 'chatgpt', name: 'ChatGPT', cat: 'AI', color: '#0E8F6A', file: 'images/logos/chatgpt.svg', domains: ['chatgpt.com', 'openai.com'] },
  { id: 'deepseek', name: 'DeepSeek', cat: 'AI', color: '#3355E0', file: 'images/logos/deepseek.svg', domains: ['deepseek.com', 'chat.deepseek.com'] },
  { id: 'toutiao', name: '今日头条', cat: '资讯', color: '#E53030', file: 'images/logos/toutiao.svg', domains: ['toutiao.com'] },
  { id: 'tencent-news', name: '腾讯新闻', cat: '资讯', color: '#0E7BD6', file: 'images/logos/tencent-news.svg', domains: ['news.qq.com'] },
];

export const PRESET_CATEGORIES = ['搜索', '视频', '社交', '开发', '购物', '工具', '音乐', 'AI', '资讯'];
